### ISSUE TITLE
STT package NOT in npm,someone pls upload or help.

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [coqui-ai/STT-examples#48]
error log>npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/STT - Not found
npm ERR! 404
npm ERR! 404  'STT@^1.3.0' is not in this registry.
npm ERR! 404 This package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by reuben** [comment]
Looks like npmjs started erroring out instead of lowering the case automatically. This is the package: https://www.npmjs.com/package/stt

**Comment by RESDXChgfore9hing** [comment]
i think we should edit the example and do a pr
