### ISSUE TITLE
examples outdated

### ISSUE THREAD

**Issue by davidak** [coqui-ai/STT-examples#5]
https://github.com/coqui-ai/STT-examples/tree/r0.9/vad_transcriber

e.g. contains link to https://github.com/coqui-ai/STT-examples/blob/doc/audioTranscript.png 404

and mozilla references

**Comment by johns10** [comment]
The WASM example appears to contain a link to a model that doesn't exist https://github.com/coqui-ai/STT-examples/tree/r1.0/wasm.

Is the WASM release still being maintained?

**Comment by johns10** [comment]
I was able to get the download to work by grabbing the alpha at https://github.com/coqui-ai/STT/releases/download/v1.4.0-alpha.6/libstt.tflite.wasm.zip

**Comment by reuben** [comment]
The example is not outdated, it's too new :)

The link will work once we make a stable release with the WASM package.

**Comment by johns10** [comment]
Beauty. It's "working" with WASM. I'll keep playing.
